# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
# This workflow contains two jobs, build and mathcomp:
jobs:
  build:
    # The type of runner that the job will run on;
    # the OS must be GNU/Linux to be able to use the docker-coq-action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
          - 'latest'
        ocaml_version:
          - '4.09-flambda'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: '.opam'
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
