name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1.1.0
        with:
          opam_file: 'coq-tactician-dummy.opam'
